ECommerce.UI/Areas/Admin/Controllers/ProductsController.cs
using ECommerce.Core.Dtos;
using ECommerce.Core.Enums;
using ECommerce.Core.Exceptions;
using ECommerce.Core.Helpers;
using ECommerce.Core.ServiceContracts.Categories;
using ECommerce.Core.ServiceContracts.Images;
using ECommerce.Core.ServiceContracts.Manufacturers;
using ECommerce.Core.ServiceContracts.Products;
using ECommerce.Core.Settings;
using ECommerce.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;

namespace ECommerce.UI.Areas.Admin.Controllers
{
    /// <summary>
    /// Controller for managing products in the admin area.
    /// </summary>
    [Area("Admin")]
    [Authorize(Roles = Constants.ROLE_ADMIN)]
    public class ProductsController : Controller
    {
        private readonly IProductGetterService _productGetterService;
        private readonly IProductAdderService _productAdderService;
        private readonly IProductUpdaterService _productUpdaterService;
        private readonly IProductDeleterService _productDeleterService;

        private readonly ICategoryGetterService _categoryGetterService;
        private readonly ICategorySorterService _categorySorterService;
        private readonly IManufacturerGetterService _manufacturerGetterService;
        private readonly IManufacturerSorterService _manufacturerSorterService;

        private readonly IWebHostEnvironment _webHostEnvironment;

        private readonly IImageUploaderService _imageUploaderService;
        private readonly IImageDeleterService _imageDeleterService;
        private readonly ImageUploadOptions _imageUploadOptions;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductsController"/> class.
        /// </summary>
        /// <param name="productGetterService">The service for retrieving products.</param>
        /// <param name="productAdderService">The service for adding products.</param>
        /// <param name="productUpdaterService">The service for updating products.</param>
        /// <param name="productDeleterService">The service for deleting products.</param>
        /// <param name="categoryGetterService">The service for retrieving categories.</param>
        /// <param name="categorySorterService">The service for sorting categories.</param>
        /// <param name="manufacturerGetterService">The service for retrieving manufacturers.</param>
        /// <param name="manufacturerSorterService">The service for sorting manufacturers.</param>
        /// <param name="webHostEnvironment">The hosting environment.</param>
        /// <param name="imageUploaderService">The service for uploading images.</param>
        /// <param name="imageDeleterService">The service for deleting images.</param>
        /// <param name="imageUploadOptions">The image upload options.</param>
        public ProductsController(IProductGetterService productGetterService,
            IProductAdderService productAdderService, IProductUpdaterService productUpdaterService,
            IProductDeleterService productDeleterService, ICategoryGetterService categoryGetterService,
            ICategorySorterService categorySorterService, IManufacturerGetterService manufacturerGetterService,
            IManufacturerSorterService manufacturerSorterService, IWebHostEnvironment webHostEnvironment,
            IImageUploaderService imageUploaderService, IImageDeleterService imageDeleterService,
            IOptions<ImageUploadOptions> imageUploadOptions)
        {
            _productGetterService = productGetterService;
            _productAdderService = productAdderService;
            _productUpdaterService = productUpdaterService;
            _productDeleterService = productDeleterService;

            _categoryGetterService = categoryGetterService;
            _categorySorterService = categorySorterService;
            _manufacturerGetterService = manufacturerGetterService;
            _manufacturerSorterService = manufacturerSorterService;

            _webHostEnvironment = webHostEnvironment;

            _imageUploaderService = imageUploaderService;
            _imageDeleterService = imageDeleterService;
            _imageUploadOptions = imageUploadOptions.Value;
        }

        /// <summary>
        /// Displays the index view.
        /// </summary>
        /// <returns>The index view.</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Displays the view for adding or updating a product.
        /// </summary>
        /// <param name="id">The ID of the product to update, if any.</param>
        /// <returns>The view for adding or updating a product.</returns>
        [HttpGet]
        public async Task<IActionResult> Upsert(Guid? id)
        {
            var productUpsertModel = new ProductUpsertViewModel()
            {
                Categories = await GetCategoriesSelectList(),
                Manufacturers = await GetManufacturersSelectList(),
                ImageUploadOptions = _imageUploadOptions
            };

            if (id is not null && id != Guid.Empty)
            {
                productUpsertModel.Product = await _productGetterService.GetByIdAsync(id.Value)
                ?? new ProductDto();
            }

            return View(productUpsertModel);
        }

        /// <summary>
        /// Handles the POST request for adding or updating a product.
        /// </summary>
        /// <param name="productModel">The product data to add or update.</param>
        /// <returns>The index view if successful, otherwise the add/update view.</returns>
        [HttpPost]
        public async Task<IActionResult> Upsert(ProductUpsertViewModel productModel)
        {
            if (!productModel.Categories.Any())
            {
                productModel.Categories = await GetCategoriesSelectList();
            }
            if (!productModel.Manufacturers.Any())
            {
                productModel.Manufacturers = await GetManufacturersSelectList();
            }
            productModel.ImageUploadOptions ??= _imageUploadOptions;

            if (!ModelState.IsValid)
            {
                return View(productModel);
            }

            try
            {
                ProductDto productResponse;

                if (productModel.Product.Id == Guid.Empty)
                {
                    productResponse = await _productAdderService.AddAsync(productModel.Product);
                }
                else
                {
                    productResponse = await _productUpdaterService.UpdateAsync(productModel.Product);
                }

                if (productModel.Image is not null)
                {
                    try
                    {
                        var imageUrl = await _imageUploaderService.UploadAsync(productModel.Image,
                            productResponse.Id.ToString());

                        _imageDeleterService.DeleteImage(productResponse.ImageUrl);

                        productResponse.ImageUrl = imageUrl;

                        await _productUpdaterService.UpdateAsync(productResponse);
                    }
                    catch (ImageUploadException ex)
                    {
                        ModelState.AddModelError(nameof(productModel.Image), ex.Message);
                        TempData["error"] = ex.Message;
                        return View(productModel);
                    }
                    catch (Exception)
                    {
                        TempData["error"] = "Failed to add the image.";
                        return View(productModel);
                    }
                }

                TempData["success"] = $"Product {(productModel.Product.Id == Guid.Empty
                    ? "created" : "updated")} successfully.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                TempData["error"] = "An error occurred. Please try again.";
                return View(productModel);
            }
        }

        #region API

        /// <summary>
        /// Checks if a product name is unique.
        /// </summary>
        /// <param name="product">The product DTO containing the name to check.</param>
        /// <returns>A JSON result indicating whether the name of the product is unique.</returns>
        [HttpGet]
        public async Task<IActionResult> IsProductNameUnique(ProductDto product)
        {
            if (product.Id != Guid.Empty)
            {
                var existingProduct = await _productGetterService.GetByIdAsync(product.Id);

                if (existingProduct is not null && existingProduct.Name == product.Name)
                {
                    return Json(true);
                }
            }

            var categorys = await _productGetterService.GetAllAsync();

            if (categorys.Any(t => t.Name == product.Name))
            {
                return Json(false);
            }

            return Json(true);
        }

        /// <summary>
        /// Retrieves all products.
        /// </summary>
        /// <returns>A JSON result containing the list of products.</returns>
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            try
            {
                List<ProductDto> products = await _productGetterService.GetAllAsync();

                return Ok(new { data = products });
            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError,
                    new { error = Constants.GENERIC_ERROR_MESSAGE });
            }
        }

        /// <summary>
        /// Deletes a product by ID.
        /// </summary>
        /// <param name="id">The ID of the product to delete.</param>

ECommerce.UI/Controllers/ShoppingCartController.cs
using ECommerce.Core.Exceptions;
using ECommerce.Core.Helpers;
using ECommerce.Core.ServiceContracts.ShoppingCartItems;
using ECommerce.Core.ServiceContracts.Users;
using ECommerce.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ECommerce.UI.Controllers
{
    /// <summary>
    /// Controller responsible for managing shopping cart-related actions, such as adding, 
    /// removing, and updating items in the shopping cart.
    /// </summary>
    [Authorize(Roles = Constants.ROLE_CUSTOMER)]
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartItemGetterService _shoppingCartItemGetterService;
        private readonly IShoppingCartItemDeleterService _shoppingCartItemDeleterService;
        private readonly IShoppingCartItemUpdaterService _shoppingCartItemUpdaterService;
        private readonly IUserContextService _userContextService;

        /// <summary>
        /// Initializes a new instance of the <see cref="ShoppingCartController"/> class.
        /// </summary>
        /// <param name="shoppingCartItemGetterService">The shopping cart item getter service.</param>
        /// <param name="shoppingCartItemDeleterService">The shopping cart item deleter service.</param>
        /// <param name="shoppingCartItemUpdaterService">The shopping cart item updater service.</param>
        /// <param name="userContextService">The user context service.</param>
        public ShoppingCartController(IShoppingCartItemGetterService shoppingCartItemGetterService,
            IShoppingCartItemDeleterService shoppingCartItemDeleterService,
            IShoppingCartItemUpdaterService shoppingCartItemUpdaterService,
            IUserContextService userContextService)
        {
            _shoppingCartItemGetterService = shoppingCartItemGetterService;
            _shoppingCartItemDeleterService = shoppingCartItemDeleterService;
            _shoppingCartItemUpdaterService = shoppingCartItemUpdaterService;
            _userContextService = userContextService;
        }

        /// <summary>
        /// Displays the shopping cart with all items added by the current customer.
        /// </summary>
        /// <returns>The shopping cart view.</returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var customerId = _userContextService.GetCustomerId(User.Identity as ClaimsIdentity);

            var items = await _shoppingCartItemGetterService.GetByCustomerIdAsync(customerId!.Value);
            decimal totalPrice = items.Sum(i => i.Count * i.ProductPrice!.Value);

            var shoppingCartViewModel = new ShoppingCartViewModel()
            {
                Items = items,
                TotalPrice = totalPrice
            };

            return View(shoppingCartViewModel);
        }

        /// <summary>
        /// Decreases the quantity of a product in the shopping cart and redirects to the shopping cart page.
        /// </summary>
        /// <param name="id">The ID of the shopping cart item to decrease.</param>
        /// <returns>A redirect to the shopping cart page.</returns>
        [HttpGet]
        public async Task<IActionResult> Minus(Guid id)
        {
            var cart = await _shoppingCartItemGetterService.GetByIdAsync(id);

            if (cart is null)
            {
                TempData["error"] = "Product not found.";
            }
            else
            {
                if (cart.Count == 1)
                {
                    await _shoppingCartItemDeleterService.DeleteAsync(id);
                }
                else
                {
                    cart.Count -= 1;
                    await _shoppingCartItemUpdaterService.UpdateAsync(cart);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Increases the quantity of a product in the shopping cart and redirects to the shopping cart page.
        /// </summary>
        /// <param name="id">The ID of the shopping cart item to increase.</param>
        /// <returns>A redirect to the shopping cart page.</returns>
        [HttpGet]
        public async Task<IActionResult> Plus(Guid id)
        {
            var cart = await _shoppingCartItemGetterService.GetByIdAsync(id);

            if (cart is null)
            {
                TempData["error"] = "Product not found.";
            }
            else
            {
                cart.Count += 1;
                try
                {
                    await _shoppingCartItemUpdaterService.UpdateAsync(cart);
                }
                catch (QuantityExceedsStockException ex)
                {
                    TempData["error"] = ex.Message;
                }
                catch (Exception)
                {
                    TempData["error"] = Constants.GENERIC_ERROR_MESSAGE;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Removes a product from the shopping cart and redirects to the shopping cart page.
        /// </summary>
        /// <param name="id">The ID of the shopping cart item to remove.</param>
        /// <returns>A redirect to the shopping cart page.</returns>
        [HttpGet]
        public async Task<IActionResult> Remove(Guid id)
        {
            var cart = await _shoppingCartItemGetterService.GetByIdAsync(id);

            if (cart is null)
            {
                TempData["error"] = "Product not found.";
            }
            else
            {
                try
                {
                    await _shoppingCartItemDeleterService.DeleteAsync(id);
                }
                catch (Exception)
                {
                    TempData["error"] = Constants.GENERIC_ERROR_MESSAGE;
                }
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ECommerce.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.3/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid px-4 mx-4">
                <a class="navbar-brand me-3">ABC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item me-1">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(Constants.ROLE_CUSTOMER))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-action="@nameof(ShoppingCartController.Index)"
                                   asp-controller="ShoppingCart">
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                        }
                        @if (User.IsInRole(Constants.ROLE_ADMIN))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin"
                                           asp-controller="Categories" asp-action="Index">Categories</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin"
                                           asp-controller="Manufacturers" asp-action="Index">Manufacturers</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin"
                                           asp-controller="Products" asp-action="Index">Products</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>

                    <div class="navbar-text d-flex">
                        @if (User.Identity!.IsAuthenticated)
                        {
                            <div class="nav-item fw-bol me-4">@User.Identity.Name</div>
                            <div class="nav-item">
                                <a asp-action="@nameof(AccountController.Logout)" asp-controller="Account"
                                   asp-area=""
                                   class="nav-link">Log out</a>
                            </div>

                        }
                        else
                        {

                            <a asp-action="@nameof(AccountController.Login)" asp-controller="Account"
                               class="nav-link">
                                Login
                            </a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-light">
        <div class="container">
            &copy; @(DateTime.Now.Year) - ABC - <a class="link-secondary" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/2.0.3/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <partial name="_NotificationPartial.cshtml" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ECommerce.UI/Views/Shared/_NotificationPartial.cshtml
@if(TempData["error"] is not null)
{
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}
@if (TempData["success"] is not null)
{
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}